[workspace]
resolver = "2"
members = [
  "engenho",
  "engenho-types",
  "engenho-cluster-config",
  "engenho-cluster-config-render",
  "engenho-kube-client",
  "engenho-kube-codegen",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.89.0"
license = "MIT"
repository = "https://github.com/pleme-io/engenho"
authors = ["pleme-io"]

[workspace.dependencies]
engenho-types          = { path = "engenho-types" }
engenho-cluster-config = { path = "engenho-cluster-config" }
engenho-kube-client    = { path = "engenho-kube-client" }
serde                  = { version = "1.0", features = ["derive"] }
serde_yaml             = "0.9"
serde_json             = "1.0"
thiserror              = "2.0"
indoc                  = "2.0"

[workspace.lints]

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"

[profile]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
