;; Generated by repo-forge new --archetype rust-substrate-workspace-tool
;; Edit this file + run `repo-forge migrate .` to rewrite artifacts.

(defrepo engenho
  :description "Typed, attested, Rust-native Kubernetes runtime"
  :kind :rust-workspace-tool
  :visibility :private
  :binary "engenho"
  :package-name "engenho"
  :workspace-members ("engenho-types")
;; archetype: rust-substrate-workspace-tool
;; bindings:
;;   name = "engenho"
;;   description = "Typed, attested, Rust-native Kubernetes runtime"
;;   toolName = "engenho"
;;   packageName = "engenho"
;;   workspaceMembers = "engenho-types"
)
