//! W2 / plan T4.6 — the typed border: `?fieldValidation=`, unknown and
//! duplicate fields, and a typed decode per catalog row.
//!
//! ## Where the expected values come from
//!
//! * **The fixtures** under `tests/fixtures/k8s-api-v0.34.1/` are copied
//!   byte-for-byte from `k8s.io/api@v0.34.1/testdata/HEAD/<group>.<version>.
//!   <Kind>.json` — upstream's roundtrip fixtures, generated by fuzzing EVERY
//!   field of the Go type. One per schema-backed catalog row. A fixture that
//!   yields an unknown field means engenho's schema lacks a field the Go
//!   struct has (a false refusal under kubectl's default `Strict`).
//! * **Which fixture objects are Go maps** is read off the fuzzer's own
//!   naming (a map it fills has the single key `<field>Key`, e.g.
//!   `"labels": {"labelsKey": ...}`), not off the `OpenAPI` document the
//!   code under test lowers — so the planted-key test cannot agree with the
//!   code by sharing its mistake. `FieldsV1` and `RawExtension` keep their
//!   bytes (`apimachinery` `meta/v1/types.go`, `runtime/types.go` — both
//!   implement `UnmarshalJSON`).
//! * **The directive's semantics and wording**:
//!   `k8s.io/apiserver@v0.35.0/pkg/endpoints/handlers/{rest,create,update,patch}.go`
//!   (`fieldValidation()` defaults to Warn; Strict → `transformDecodeError`
//!   400 on POST/PUT, `NewInvalid` 422 over `patch` on PATCH),
//!   `k8s.io/apimachinery@v0.34.1/pkg/apis/meta/v1/validation/validation.go`
//!   (`ValidateFieldValidation`), `sigs.k8s.io/json` `kubernetes_patch.go`
//!   (`unknown field "<path>"`, `duplicate field "<path>"`, path syntax),
//!   and `k8s.io/apiserver` `endpoints/filters/warning.go` (`299 - "<text>"`).
//!
//! ## What is pinned as a deviation, not as truth
//!
//! [`TYPED_DECODE_DEVIATIONS`]: bodies upstream accepts that engenho's
//! generated structs refuse today. They are why the typed decode runs in
//! Shadow; each entry names the struct defect. A fix in engenho-types turns
//! its entry red here, and the entry is deleted — the ratchet only tightens.

use std::collections::BTreeSet;
use std::sync::Arc;
use std::time::Duration;

use engenho_apiserver::field_validation::{
    Directive, FieldValidation, KindRef, Warnings, check_object,
};
use engenho_apiserver::typed_decode::typed_row;
use engenho_apiserver::{ApiServer, ResourceHandler, RouterState, StoreBackedHandler};
use engenho_store::command::{Reason, ResourceCommand};
use engenho_store::{InProcessRouter, ResourceKey, StoreMesh, default_config};
use engenho_substrate::WouldRejectLedger;
use engenho_types::generated_v1_34::{RESOURCE_CATALOG, ResourceDescriptor};
use reqwest::header::WARNING;
use reqwest::{Client, StatusCode};
use serde_json::{Value, json};

// ── the upstream fixtures ──────────────────────────────────────────────────

const FIXTURES: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/k8s-api-v0.34.1/"
);

struct Fixture {
    row: &'static ResourceDescriptor,
    raw: Vec<u8>,
    value: Value,
}

impl Fixture {
    fn kind(&self) -> KindRef<'static> {
        KindRef {
            group: self.row.group,
            version: self.row.version,
            kind: self.row.kind,
            api_version: self.row.api_version,
        }
    }
}

fn fixtures() -> Vec<Fixture> {
    let rows: Vec<_> = RESOURCE_CATALOG.iter().filter(|d| !d.opaque).collect();
    assert!(rows.len() >= 39, "every schema-backed row is covered");
    rows.into_iter()
        .map(|row| {
            let group = if row.group.is_empty() {
                "core"
            } else {
                row.group
            };
            let file = [FIXTURES, group, ".", row.version, ".", row.kind, ".json"].concat();
            let raw = std::fs::read(&file).unwrap_or_else(|e| panic!("{file}: {e}"));
            let value = serde_json::from_slice(&raw).expect("fixture is JSON");
            Fixture { row, raw, value }
        })
        .collect()
}

#[test]
fn every_rows_upstream_fixture_passes_strict_and_loses_nothing() {
    for fixture in fixtures() {
        let mut value = fixture.value.clone();
        let mut warnings = Warnings::default();
        let verdict = check_object(
            Directive::asked(FieldValidation::Strict),
            fixture.kind(),
            Some(&fixture.raw),
            &mut value,
            &mut warnings,
        );
        assert!(
            verdict.is_ok(),
            "{}: upstream's own fixture is refused: {verdict:?}",
            fixture.row.kind
        );
        assert_eq!(
            value, fixture.value,
            "{}: a field was dropped",
            fixture.row.kind
        );
        assert!(warnings.texts().is_empty(), "{}", fixture.row.kind);
    }
}

/// How the fuzzer-filled fixture holds a JSON object, judged without the
/// schema: see the module docs.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Held {
    Struct,
    Map,
    Raw,
}

fn held(kind: &str, path: &[String], field: &str, object: &serde_json::Map<String, Value>) -> Held {
    let map_key = [field, "Key"].concat();
    if field == "fieldsV1" || (kind == "ControllerRevision" && path == ["data"]) {
        Held::Raw
    } else if !object.is_empty() && object.keys().all(|k| *k == map_key) {
        Held::Map
    } else {
        Held::Struct
    }
}

const PLANTED: &str = "zzPlanted";

/// Plant [`PLANTED`] in every object of `value`. Returns the rendered path
/// of every plant inside a struct (what must be reported and dropped), in
/// the value's own order, and the value as it must look after the drop.
fn plant(kind: &str, value: &mut Value) -> (Vec<String>, Value) {
    fn go(
        kind: &str,
        value: &mut Value,
        path: &mut Vec<String>,
        rendered: &str,
        field: &str,
        held_by: Held,
        out: &mut Vec<String>,
    ) -> Value {
        match value {
            Value::Object(object) => {
                let this = if held_by == Held::Raw {
                    Held::Raw
                } else {
                    held(kind, path, field, object)
                };
                let mut kept = serde_json::Map::new();
                let keys: Vec<String> = object.keys().cloned().collect();
                for key in keys {
                    let child_rendered = if rendered.is_empty() {
                        key.clone()
                    } else {
                        [rendered, ".", &key].concat()
                    };
                    let child_field = if this == Held::Map {
                        field
                    } else {
                        key.as_str()
                    };
                    path.push(key.clone());
                    let child = object.get_mut(&key).expect("present");
                    let expected = go(kind, child, path, &child_rendered, child_field, this, out);
                    path.pop();
                    kept.insert(key, expected);
                }
                let planted_at = if rendered.is_empty() {
                    PLANTED.to_owned()
                } else {
                    [rendered, ".", PLANTED].concat()
                };
                object.insert(PLANTED.to_owned(), json!("planted"));
                if this == Held::Struct {
                    out.push(planted_at);
                } else {
                    kept.insert(PLANTED.to_owned(), json!("planted"));
                }
                Value::Object(kept)
            }
            Value::Array(items) => {
                let mut kept = Vec::new();
                for (i, item) in items.iter_mut().enumerate() {
                    let child_rendered = [rendered, "[", &i.to_string(), "]"].concat();
                    kept.push(go(kind, item, path, &child_rendered, field, held_by, out));
                }
                Value::Array(kept)
            }
            other => other.clone(),
        }
    }
    let mut out = Vec::new();
    let expected = go(kind, value, &mut Vec::new(), "", "", Held::Struct, &mut out);
    (out, expected)
}

#[test]
fn an_unknown_key_planted_in_every_struct_is_dropped_and_nowhere_else() {
    let mut planted_total = 0;
    for fixture in fixtures() {
        let mut value = fixture.value.clone();
        let (in_structs, after_drop) = plant(fixture.row.kind, &mut value);
        assert!(!in_structs.is_empty(), "{}", fixture.row.kind);
        planted_total += in_structs.len();
        let raw = serde_json::to_vec(&value).expect("serializes");

        // Ignore still drops every one of them — uncapped — and nothing else.
        let mut dropped = value.clone();
        check_object(
            Directive::asked(FieldValidation::Ignore),
            fixture.kind(),
            Some(&raw),
            &mut dropped,
            &mut Warnings::default(),
        )
        .expect("ignore never refuses");
        assert_eq!(dropped, after_drop, "{}", fixture.row.kind);

        // Warn names them in document order, up to upstream's cap.
        let mut warnings = Warnings::default();
        check_object(
            Directive::asked(FieldValidation::Warn),
            fixture.kind(),
            Some(&raw),
            &mut value.clone(),
            &mut warnings,
        )
        .expect("warn never refuses");
        let want: Vec<String> = in_structs
            .iter()
            .take(engenho_apiserver::field_validation::MAX_FINDINGS)
            .map(|p| ["unknown field \"", p, "\""].concat())
            .collect();
        assert_eq!(warnings.texts(), want.as_slice(), "{}", fixture.row.kind);

        // Strict refuses.
        assert!(
            check_object(
                Directive::asked(FieldValidation::Strict),
                fixture.kind(),
                Some(&raw),
                &mut value.clone(),
                &mut Warnings::default(),
            )
            .is_err(),
            "{}",
            fixture.row.kind
        );
    }
    assert!(
        planted_total > 3000,
        "the fixtures hold {planted_total} structs"
    );
}

/// Bodies upstream accepts that a generated struct refuses today, as
/// `(kind, case, why)`. See the module docs.
const TYPED_DECODE_DEVIATIONS: &[(&str, &str, &str)] = &[
    (
        "Pod",
        "numeric quantity",
        "engenho-types `Quantity(pub String)` refuses a JSON number; upstream's \
         Quantity.UnmarshalJSON takes a number or a string",
    ),
    (
        "Pod",
        "fixture",
        "engenho-types decodes `status.phase` into a closed enum \
         (Pending|Running|Succeeded|Failed|Unknown); upstream's PodPhase is a Go \
         string and decodes `phaseValue`",
    ),
    (
        "PodDisruptionBudget",
        "fixture",
        "engenho-types decodes a `metav1.Time` map value as a non-null string; \
         upstream's zero Time is JSON null (`status.disruptedPods.<pod>: null`)",
    ),
];

/// Refused in EVERY row's fixture, so pinned once rather than per row:
/// engenho-types' `ManagedFieldsOperation` is a closed enum `{Apply,
/// Update}`, while upstream's `ManagedFieldsOperationType` is a Go string
/// that decodes any value (the fixture carries `operationValue`). The
/// fixtures are also decoded with that one field set to `Update`, so the
/// defect cannot hide any other.
const MANAGED_FIELDS_OPERATION: &str = "unknown variant `operationValue`";

/// The accept-set: bodies upstream decodes, beyond the fixtures.
fn accept_set() -> Vec<(&'static str, &'static str, Value)> {
    vec![(
        "Pod",
        "numeric quantity",
        json!({
            "apiVersion": "v1", "kind": "Pod", "metadata": {"name": "p"},
            "spec": {"containers": [{"name": "c", "image": "i",
                "resources": {"limits": {"cpu": 1, "memory": "1Gi"}}}]}
        }),
    )]
}

/// `value` with every `managedFields[].operation` set to `Update`.
fn with_known_operations(value: &Value) -> Value {
    match value {
        Value::Object(object) => Value::Object(
            object
                .iter()
                .map(|(key, child)| {
                    let child = match (key.as_str(), child) {
                        ("managedFields", Value::Array(entries)) => Value::Array(
                            entries
                                .iter()
                                .map(|entry| {
                                    let mut entry = with_known_operations(entry);
                                    entry["operation"] = json!("Update");
                                    entry
                                })
                                .collect(),
                        ),
                        _ => with_known_operations(child),
                    };
                    (key.clone(), child)
                })
                .collect(),
        ),
        Value::Array(items) => Value::Array(items.iter().map(with_known_operations).collect()),
        other => other.clone(),
    }
}

#[test]
fn every_rows_generated_struct_decodes_its_upstream_fixture_and_the_accept_set() {
    let mut refused = BTreeSet::new();
    for fixture in fixtures() {
        let row = typed_row(fixture.row.group, fixture.row.version, fixture.row.kind)
            .unwrap_or_else(|| panic!("{}: no typed row", fixture.row.kind));
        let as_is = row
            .decode(&fixture.value)
            .expect_err("pinned: the fixture's managedFields operation is refused");
        assert!(
            as_is.to_string().contains(MANAGED_FIELDS_OPERATION),
            "{}: {as_is}",
            fixture.row.kind
        );
        if let Err(e) = row.decode(&with_known_operations(&fixture.value)) {
            eprintln!("{} fixture: {e}", fixture.row.kind);
            refused.insert((fixture.row.kind, "fixture"));
        }
    }
    for (kind, case, body) in accept_set() {
        let row = RESOURCE_CATALOG
            .iter()
            .find(|d| d.kind == kind)
            .and_then(|d| typed_row(d.group, d.version, d.kind))
            .expect("typed row");
        if let Err(e) = row.decode(&body) {
            eprintln!("{kind} {case}: {e}");
            refused.insert((kind, case));
        }
    }
    let pinned: BTreeSet<_> = TYPED_DECODE_DEVIATIONS
        .iter()
        .map(|&(kind, case, _)| (kind, case))
        .collect();
    assert_eq!(
        refused, pinned,
        "the typed decode refuses exactly the pinned deviations; a fixed one is deleted \
         from TYPED_DECODE_DEVIATIONS, a new one is a regression"
    );
}

// ── through the router ─────────────────────────────────────────────────────

const CONFIGMAPS: &str = "api/v1/namespaces/default/configmaps";
const DEPLOYMENTS: &str = "apis/apps/v1/namespaces/default/deployments";
const PODS: &str = "api/v1/namespaces/default/pods";
const SLICES: &str = "apis/discovery.k8s.io/v1/namespaces/default/endpointslices";

struct Cluster {
    _server: ApiServer,
    store: Arc<StoreMesh>,
    ledger: Arc<WouldRejectLedger>,
    base: String,
    client: Client,
}

struct Answer {
    status: StatusCode,
    warnings: Vec<String>,
    body: Value,
}

impl Cluster {
    async fn boot(name: &str) -> Self {
        let router = InProcessRouter::new();
        let cfg = default_config(name).expect("store config");
        let store = Arc::new(
            StoreMesh::start(1, "in-process://1".into(), router, cfg)
                .await
                .expect("store starts"),
        );
        store.initialize_singleton().await.expect("singleton init");
        assert!(store.wait_for_leadership(Duration::from_secs(3)).await);
        let handlers: Vec<Arc<dyn ResourceHandler>> =
            ["ConfigMap", "Deployment", "Pod", "EndpointSlice"]
                .into_iter()
                .map(|kind| {
                    Arc::new(StoreBackedHandler::for_kind(store.clone(), kind).expect("cataloged"))
                        as Arc<dyn ResourceHandler>
                })
                .collect();
        let ledger = Arc::new(WouldRejectLedger::new(|_| {}));
        let state = RouterState::new(handlers).with_would_reject_ledger(ledger.clone());
        let server = ApiServer::start_with_state("127.0.0.1:0".parse().expect("addr"), state, None)
            .await
            .expect("server starts");
        let base = ["http://", &server.local_addr().to_string(), "/"].concat();
        Self {
            _server: server,
            store,
            ledger,
            base,
            client: Client::new(),
        }
    }

    fn url(&self, collection: &str, name: Option<&str>, directive: Option<&str>) -> String {
        let mut url = [&self.base, collection].concat();
        if let Some(name) = name {
            url.push('/');
            url.push_str(name);
        }
        if let Some(directive) = directive {
            url.push_str("?fieldValidation=");
            url.push_str(directive);
        }
        url
    }

    async fn send(&self, request: reqwest::RequestBuilder) -> Answer {
        let resp = request.send().await.expect("sent");
        let status = resp.status();
        let warnings = resp
            .headers()
            .get_all(WARNING)
            .iter()
            .map(|v| v.to_str().expect("ascii").to_owned())
            .collect();
        let body = resp.json().await.unwrap_or(Value::Null);
        Answer {
            status,
            warnings,
            body,
        }
    }

    async fn post(&self, collection: &str, directive: Option<&str>, raw: &str) -> Answer {
        self.send(
            self.client
                .post(self.url(collection, None, directive))
                .header("Content-Type", "application/json")
                .body(raw.to_owned()),
        )
        .await
    }

    async fn put(
        &self,
        collection: &str,
        name: &str,
        directive: Option<&str>,
        raw: &str,
    ) -> Answer {
        self.send(
            self.client
                .put(self.url(collection, Some(name), directive))
                .header("Content-Type", "application/json")
                .body(raw.to_owned()),
        )
        .await
    }

    async fn patch(
        &self,
        collection: &str,
        name: &str,
        query: &str,
        content_type: &str,
        raw: &str,
    ) -> Answer {
        let url = [&self.url(collection, Some(name), None), "?", query].concat();
        self.send(
            self.client
                .patch(url)
                .header("Content-Type", content_type)
                .body(raw.to_owned()),
        )
        .await
    }

    async fn get(&self, collection: &str, name: &str) -> Answer {
        self.send(self.client.get(self.url(collection, Some(name), None)))
            .await
    }
}

fn warning(text: &str) -> String {
    let mut header = String::from("299 - \"");
    header.push_str(&text.replace('\\', "\\\\").replace('"', "\\\""));
    header.push('"');
    header
}

/// A ConfigMap body with a repeated `metadata.name` (the last one, `b`, is
/// the one that counts) and a misspelled `data`.
const CM_UNKNOWN_AND_DUPLICATE: &str = r#"{"apiVersion":"v1","kind":"ConfigMap",
    "metadata":{"name":"a","name":"b"},"dta":{"k":"v"},"data":{"k":"v"}}"#;

#[tokio::test]
async fn post_strict_refuses_naming_every_finding_and_stores_nothing() {
    let c = Cluster::boot("w2-post-strict").await;
    let a = c
        .post(CONFIGMAPS, Some("Strict"), CM_UNKNOWN_AND_DUPLICATE)
        .await;
    assert_eq!(a.status, StatusCode::BAD_REQUEST, "{:?}", a.body);
    assert_eq!(a.body["reason"], "BadRequest");
    let message = a.body["message"].as_str().expect("message");
    assert!(
        message.ends_with(
            "ConfigMap in version \"v1\" cannot be handled as a ConfigMap: strict decoding \
             error: duplicate field \"metadata.name\", unknown field \"dta\""
        ),
        "{message}"
    );
    assert_eq!(c.get(CONFIGMAPS, "b").await.status, StatusCode::NOT_FOUND);
}

#[tokio::test]
async fn post_warn_and_the_default_store_without_the_field_and_say_so() {
    let c = Cluster::boot("w2-post-warn").await;
    let want = [
        warning(r#"duplicate field "metadata.name""#),
        warning(r#"unknown field "dta""#),
    ];
    for (directive, name) in [(Some("Warn"), "b"), (None, "b")] {
        let a = c
            .post(CONFIGMAPS, directive, CM_UNKNOWN_AND_DUPLICATE)
            .await;
        // The second POST of the same name is a 409; its warnings still ride.
        assert_eq!(a.warnings, want, "{directive:?}");
        if directive.is_some() {
            assert_eq!(a.status, StatusCode::CREATED, "{:?}", a.body);
        } else {
            assert_eq!(a.status, StatusCode::CONFLICT, "{:?}", a.body);
        }
        let stored = c.get(CONFIGMAPS, name).await.body;
        assert!(
            stored.get("dta").is_none(),
            "the unknown field is dropped: {stored}"
        );
        assert_eq!(stored["data"], json!({"k": "v"}));
    }
}

#[tokio::test]
async fn post_ignore_drops_the_field_and_says_nothing() {
    let c = Cluster::boot("w2-post-ignore").await;
    let a = c
        .post(CONFIGMAPS, Some("Ignore"), CM_UNKNOWN_AND_DUPLICATE)
        .await;
    assert_eq!(a.status, StatusCode::CREATED, "{:?}", a.body);
    assert!(a.warnings.is_empty(), "{:?}", a.warnings);
    assert!(a.body.get("dta").is_none(), "{}", a.body);
    assert_eq!(a.body["metadata"]["name"], "b", "the last duplicate wins");
}

#[tokio::test]
async fn an_unsupported_directive_is_upstreams_422_on_the_options() {
    let c = Cluster::boot("w2-bad-directive").await;
    let body = r#"{"apiVersion":"v1","kind":"ConfigMap","metadata":{"name":"x"}}"#;
    for (answer, options) in [
        (
            c.post(CONFIGMAPS, Some("strict"), body).await,
            "CreateOptions",
        ),
        (
            c.put(CONFIGMAPS, "x", Some("yes"), body).await,
            "UpdateOptions",
        ),
        (
            c.patch(
                CONFIGMAPS,
                "x",
                "fieldValidation=all",
                "application/merge-patch+json",
                "{}",
            )
            .await,
            "PatchOptions",
        ),
    ] {
        assert_eq!(
            answer.status,
            StatusCode::UNPROCESSABLE_ENTITY,
            "{:?}",
            answer.body
        );
        assert_eq!(answer.body["reason"], "Invalid");
        let message = answer.body["message"].as_str().expect("message");
        assert!(message.starts_with(options), "{message}");
        assert!(
            message.ends_with(r#"supported values: "", "Ignore", "Strict", "Warn""#),
            "{message}"
        );
    }
    assert_eq!(c.get(CONFIGMAPS, "x").await.status, StatusCode::NOT_FOUND);
}

#[tokio::test]
async fn put_follows_the_same_directive() {
    let c = Cluster::boot("w2-put").await;
    let created = c
        .post(
            CONFIGMAPS,
            None,
            r#"{"apiVersion":"v1","kind":"ConfigMap","metadata":{"name":"p"}}"#,
        )
        .await;
    assert_eq!(created.status, StatusCode::CREATED);
    let body = r#"{"apiVersion":"v1","kind":"ConfigMap","metadata":{"name":"p"},"dta":{}}"#;
    let strict = c.put(CONFIGMAPS, "p", Some("Strict"), body).await;
    assert_eq!(strict.status, StatusCode::BAD_REQUEST, "{:?}", strict.body);
    let warn = c.put(CONFIGMAPS, "p", Some("Warn"), body).await;
    assert_eq!(warn.status, StatusCode::OK, "{:?}", warn.body);
    assert_eq!(warn.warnings, [warning(r#"unknown field "dta""#)]);
    assert!(warn.body.get("dta").is_none());
}

fn deployment(name: &str) -> String {
    json!({
        "apiVersion": "apps/v1", "kind": "Deployment", "metadata": {"name": name},
        "spec": {"selector": {"matchLabels": {"app": name}},
                 "template": {"metadata": {"labels": {"app": name}},
                              "spec": {"containers": [{"name": "c", "image": "i"}]}}}
    })
    .to_string()
}

#[tokio::test]
async fn a_patch_is_judged_by_the_object_it_would_store() {
    let c = Cluster::boot("w2-patch").await;
    assert_eq!(
        c.post(DEPLOYMENTS, None, &deployment("d")).await.status,
        StatusCode::CREATED
    );

    // Strict merge patch with an unknown field inside a list item: 422, and
    // the object is untouched.
    let bad = r#"{"spec":{"template":{"spec":{"containers":[{"name":"c","image":"i","imagePullPolicyy":"x"}]}}}}"#;
    let strict = c
        .patch(
            DEPLOYMENTS,
            "d",
            "fieldValidation=Strict",
            "application/merge-patch+json",
            bad,
        )
        .await;
    assert_eq!(
        strict.status,
        StatusCode::UNPROCESSABLE_ENTITY,
        "{:?}",
        strict.body
    );
    assert_eq!(strict.body["reason"], "Invalid");
    let message = strict.body["message"].as_str().expect("message");
    assert!(
        message.starts_with(r#" "" is invalid: patch: Invalid value: "#),
        "{message}"
    );
    assert!(
        message.ends_with(
            r#"strict decoding error: unknown field "spec.template.spec.containers[0].imagePullPolicyy""#
        ),
        "{message}"
    );

    // Warn: applied, the field dropped, one warning.
    let warn = c
        .patch(
            DEPLOYMENTS,
            "d",
            "fieldValidation=Warn",
            "application/merge-patch+json",
            bad,
        )
        .await;
    assert_eq!(warn.status, StatusCode::OK, "{:?}", warn.body);
    assert_eq!(
        warn.warnings,
        [warning(
            r#"unknown field "spec.template.spec.containers[0].imagePullPolicyy""#
        )]
    );
    let container = &warn.body["spec"]["template"]["spec"]["containers"][0];
    assert!(container.get("imagePullPolicyy").is_none(), "{container}");

    // A strategic patch's directives are not fields: kubectl's client-side
    // apply sends this exact shape for every pod template it changes.
    let strategic = r#"{"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"c"}],
        "containers":[{"name":"c","image":"j"}]}}}}"#;
    let smp = c
        .patch(
            DEPLOYMENTS,
            "d",
            "fieldValidation=Strict",
            "application/strategic-merge-patch+json",
            strategic,
        )
        .await;
    assert_eq!(smp.status, StatusCode::OK, "{:?}", smp.body);
    assert!(smp.warnings.is_empty(), "{:?}", smp.warnings);
    let pod_spec = &smp.body["spec"]["template"]["spec"];
    assert_eq!(pod_spec["containers"][0]["image"], "j");
    assert!(
        pod_spec.get("$setElementOrder/containers").is_none(),
        "the merge's instruction is not stored as a field: {pod_spec}"
    );

    // A JSON patch: an operation's own unknown key, and a field it adds.
    let json_patch = r#"[{"op":"add","path":"/spec/paused2","value":true,"extra":1}]"#;
    let jp = c
        .patch(
            DEPLOYMENTS,
            "d",
            "fieldValidation=Warn",
            "application/json-patch+json",
            json_patch,
        )
        .await;
    assert_eq!(jp.status, StatusCode::OK, "{:?}", jp.body);
    assert_eq!(
        jp.warnings,
        [
            warning(r#"json patch unknown field "[0].extra""#),
            warning(r#"unknown field "spec.paused2""#),
        ]
    );
    assert!(jp.body["spec"].get("paused2").is_none());

    // A duplicate key in the patch bytes is the patch's finding too.
    let dup = c
        .patch(
            DEPLOYMENTS,
            "d",
            "fieldValidation=Strict",
            "application/merge-patch+json",
            r#"{"spec":{"paused":true,"paused":false}}"#,
        )
        .await;
    assert_eq!(
        dup.status,
        StatusCode::UNPROCESSABLE_ENTITY,
        "{:?}",
        dup.body
    );
    assert!(
        dup.body["message"]
            .as_str()
            .expect("message")
            .ends_with(r#"strict decoding error: duplicate field "spec.paused""#),
        "{:?}",
        dup.body
    );
}

#[tokio::test]
async fn a_patch_neither_blames_nor_deletes_a_field_it_did_not_bring() {
    let c = Cluster::boot("w2-patch-legacy").await;
    // Written before the border existed: straight into the store.
    let legacy = json!({
        "apiVersion": "v1", "kind": "ConfigMap",
        "metadata": {"name": "old", "namespace": "default"},
        "legacyField": {"kept": true}
    });
    c.store
        .propose(ResourceCommand::Put {
            key: ResourceKey::namespaced("", "v1", "ConfigMap", "default", "old"),
            value: legacy,
            expected: None,
            reason: Reason::Operator,
        })
        .await
        .expect("seeded");
    let a = c
        .patch(
            CONFIGMAPS,
            "old",
            "fieldValidation=Strict",
            "application/merge-patch+json",
            r#"{"metadata":{"labels":{"x":"y"}}}"#,
        )
        .await;
    assert_eq!(a.status, StatusCode::OK, "{:?}", a.body);
    assert!(a.warnings.is_empty(), "{:?}", a.warnings);
    assert_eq!(a.body["legacyField"], json!({"kept": true}));
    assert_eq!(a.body["metadata"]["labels"]["x"], "y");
}

#[tokio::test]
async fn an_apply_configuration_is_judged_whole() {
    let c = Cluster::boot("w2-apply").await;
    let config = r#"{"apiVersion":"v1","kind":"ConfigMap","metadata":{"name":"ap"},
        "data":{"k":"v"},"dta":{"k":"v"}}"#;
    let strict = c
        .patch(
            CONFIGMAPS,
            "ap",
            "fieldManager=w2&fieldValidation=Strict",
            "application/apply-patch+yaml",
            config,
        )
        .await;
    assert_eq!(strict.status, StatusCode::BAD_REQUEST, "{:?}", strict.body);
    assert!(
        strict.body["message"]
            .as_str()
            .expect("message")
            .ends_with(r#"strict decoding error: unknown field "dta""#),
        "{:?}",
        strict.body
    );
    assert_eq!(c.get(CONFIGMAPS, "ap").await.status, StatusCode::NOT_FOUND);

    let warn = c
        .patch(
            CONFIGMAPS,
            "ap",
            "fieldManager=w2",
            "application/apply-patch+yaml",
            config,
        )
        .await;
    assert_eq!(warn.status, StatusCode::OK, "{:?}", warn.body);
    assert_eq!(warn.warnings, [warning(r#"unknown field "dta""#)]);
    assert!(warn.body.get("dta").is_none(), "{}", warn.body);
    let owned = warn.body["metadata"]["managedFields"].to_string();
    assert!(
        !owned.contains("f:dta"),
        "no manager owns a dropped field: {owned}"
    );
}

#[tokio::test]
async fn a_kind_without_a_schema_checks_duplicates_and_says_what_it_did_not_check() {
    let c = Cluster::boot("w2-opaque").await;
    let slice = r#"{"apiVersion":"discovery.k8s.io/v1","kind":"EndpointSlice",
        "metadata":{"name":"s"},"addressType":"IPv4","endpoints":[],"anything":1}"#;
    let a = c.post(SLICES, Some("Strict"), slice).await;
    assert_eq!(a.status, StatusCode::CREATED, "{:?}", a.body);
    assert_eq!(
        a.warnings,
        [warning(
            "fieldValidation: unknown fields are not detected for EndpointSlice in \
             discovery.k8s.io/v1; only duplicate fields were checked"
        )]
    );
    assert_eq!(a.body["anything"], 1, "nothing is dropped without a schema");

    let dup = r#"{"apiVersion":"discovery.k8s.io/v1","kind":"EndpointSlice",
        "metadata":{"name":"t"},"addressType":"IPv4","addressType":"IPv6"}"#;
    let refused = c.post(SLICES, Some("Strict"), dup).await;
    assert_eq!(
        refused.status,
        StatusCode::BAD_REQUEST,
        "{:?}",
        refused.body
    );

    let quiet = c.post(SLICES, None, &slice.replace("\"s\"", "\"u\"")).await;
    assert_eq!(quiet.status, StatusCode::CREATED);
    assert!(
        quiet.warnings.is_empty(),
        "an unasked default is quiet: {:?}",
        quiet.warnings
    );
}

#[tokio::test]
async fn a_subresource_write_parses_the_directive_and_says_it_checked_nothing() {
    let c = Cluster::boot("w2-subresource").await;
    assert_eq!(
        c.post(DEPLOYMENTS, None, &deployment("s")).await.status,
        StatusCode::CREATED
    );
    let status_url = ["apis/apps/v1/namespaces/default/deployments/s/status"].concat();
    let asked = c
        .send(
            c.client
                .patch([&c.base, status_url.as_str(), "?fieldValidation=Strict"].concat())
                .header("Content-Type", "application/merge-patch+json")
                .body(r#"{"status":{"replicas":1}}"#),
        )
        .await;
    assert_eq!(asked.status, StatusCode::OK, "{:?}", asked.body);
    assert_eq!(
        asked.warnings,
        [warning(
            "fieldValidation: the status subresource is not checked for unknown or duplicate \
             fields"
        )]
    );
    let bad = c
        .send(
            c.client
                .patch([&c.base, status_url.as_str(), "?fieldValidation=nope"].concat())
                .header("Content-Type", "application/merge-patch+json")
                .body("{}"),
        )
        .await;
    assert_eq!(
        bad.status,
        StatusCode::UNPROCESSABLE_ENTITY,
        "{:?}",
        bad.body
    );
}

#[tokio::test]
async fn the_typed_decode_counts_what_its_struct_refuses_and_stores_the_body() {
    let c = Cluster::boot("w2-typed-decode").await;
    let (_, _, body) = accept_set().remove(0);
    let a = c.post(PODS, None, &body.to_string()).await;
    assert_eq!(a.status, StatusCode::CREATED, "{:?}", a.body);
    assert_eq!(
        a.body["spec"]["containers"][0]["resources"]["limits"]["cpu"], 1,
        "the original value is stored, not the struct's"
    );
    assert_eq!(c.ledger.count("typed_decode", "decode_error"), 1);

    let clean = c
        .post(
            CONFIGMAPS,
            None,
            r#"{"apiVersion":"v1","kind":"ConfigMap","metadata":{"name":"ok"}}"#,
        )
        .await;
    assert_eq!(clean.status, StatusCode::CREATED);
    assert_eq!(
        c.ledger.count("typed_decode", "decode_error"),
        1,
        "a clean body counts nothing"
    );
}
