//! Typed k3s server config — the AST that replaces the previous
//! `formatdoc!`-based emitter (★★ TYPED-EMISSION violation per
//! `pleme-io/theory/TYPED-EMISSION.md`).
//!
//! Every k3s `config.yaml` field gets a typed equivalent here. The
//! emitter is `serde_yaml::to_string`; round-trips through the
//! struct prove idempotency.

use std::collections::BTreeMap;
use std::net::Ipv4Addr;

use serde::{Deserialize, Serialize};

use crate::network::PortRange;

/// Typed view of the subset of k3s `config.yaml` engenho cares
/// about. Fields use `skip_serializing_if` so unset values
/// don't pollute the emitted YAML (k3s only consumes set keys).
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub struct K3sServerConfig {
    /// Stable node identifier (matches `--node-name`).
    pub node_name: String,

    /// `--service-node-port-range` — formatted as `start-end`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_node_port_range: Option<String>,

    /// `--tls-san` list (DNS names + IPs to embed in the API-server cert).
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub tls_san: Vec<String>,

    /// `--flannel-iface-mtu` — only emitted if explicit.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub flannel_iface_mtu: Option<u32>,

    /// `--advertise-address`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub advertise_address: Option<String>,

    /// `--bind-address`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bind_address: Option<String>,

    /// Other fields engenho doesn't model explicitly — preserved
    /// on round-trip for operator extensions.
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_yaml::Value>,
}

impl K3sServerConfig {
    /// Construct from typed primitives. Encapsulates the
    /// `port_range.start-port_range.end` formatting that was
    /// inlined via `formatdoc!` previously.
    #[must_use]
    pub fn from_typed_inputs(
        cluster_name: impl Into<String>,
        node_port_range: PortRange,
        tls_sans: &[String],
        mtu: Option<u32>,
        advertise_address: Option<Ipv4Addr>,
        bind_address: Option<Ipv4Addr>,
    ) -> Self {
        Self {
            node_name: cluster_name.into(),
            service_node_port_range: Some(format!(
                "{}-{}",
                node_port_range.start, node_port_range.end
            )),
            tls_san: tls_sans.to_vec(),
            flannel_iface_mtu: mtu,
            advertise_address: advertise_address.map(|a| a.to_string()),
            bind_address: bind_address.map(|b| b.to_string()),
            extra: BTreeMap::new(),
        }
    }

    /// Serialize to k3s-compatible YAML. Replaces the previous
    /// `formatdoc!` block. **Typed emission.**
    #[must_use]
    pub fn to_yaml(&self) -> String {
        // serde_yaml emits keys without quotes when possible; the
        // header comment is a hand-prepended single line for
        // operator-readability (k3s ignores comments).
        let body = serde_yaml::to_string(self).expect("K3sServerConfig serializes");
        format!(
            "# Generated by engenho-cluster-config for {}\n{body}",
            self.node_name
        )
    }

    /// Parse k3s `config.yaml`. Tolerant of unknown fields via
    /// the `extra` flatten map — operator extensions survive a
    /// read → modify → write cycle untouched.
    ///
    /// # Errors
    ///
    /// Returns `Err` on malformed YAML.
    pub fn from_yaml(s: &str) -> Result<Self, serde_yaml::Error> {
        serde_yaml::from_str(s)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> K3sServerConfig {
        K3sServerConfig {
            node_name: "rio".into(),
            service_node_port_range: Some("30000-32767".into()),
            tls_san: vec!["rio.cluster.local".into(), "10.0.0.1".into()],
            flannel_iface_mtu: Some(1450),
            advertise_address: Some("10.0.0.1".into()),
            bind_address: Some("0.0.0.0".into()),
            extra: BTreeMap::new(),
        }
    }

    #[test]
    fn emit_has_expected_fields() {
        let yaml = sample().to_yaml();
        // node-name uses kebab-case.
        assert!(yaml.contains("node-name: rio"));
        assert!(yaml.contains("service-node-port-range: 30000-32767"));
        assert!(yaml.contains("- rio.cluster.local"));
        assert!(yaml.contains("flannel-iface-mtu: 1450"));
        assert!(yaml.contains("advertise-address: 10.0.0.1"));
        assert!(yaml.contains("bind-address: 0.0.0.0"));
        // Header comment present.
        assert!(yaml.starts_with("# Generated by engenho-cluster-config for rio"));
    }

    #[test]
    fn emit_skips_optional_unset_fields() {
        let cfg = K3sServerConfig {
            node_name: "minimal".into(),
            service_node_port_range: None,
            tls_san: vec![],
            flannel_iface_mtu: None,
            advertise_address: None,
            bind_address: None,
            extra: BTreeMap::new(),
        };
        let yaml = cfg.to_yaml();
        assert!(!yaml.contains("service-node-port-range"));
        assert!(!yaml.contains("tls-san"));
        assert!(!yaml.contains("flannel-iface-mtu"));
        assert!(!yaml.contains("advertise-address"));
        assert!(!yaml.contains("bind-address"));
        assert!(yaml.contains("node-name: minimal"));
    }

    /// Round-trip property: parsing emit produces the input
    /// (modulo the header comment which serde_yaml strips on read).
    #[test]
    fn round_trip_through_yaml() {
        let original = sample();
        let yaml = original.to_yaml();
        // Strip leading comment lines before parsing.
        let body: String = yaml.lines().skip(1).collect::<Vec<_>>().join("\n");
        let parsed = K3sServerConfig::from_yaml(&body).unwrap();
        assert_eq!(parsed, original);
    }

    #[test]
    fn parse_preserves_unknown_fields_via_extra() {
        let yaml = "\
node-name: x
unknown-operator-key: hello
nested-extra:
  a: 1
  b: 2
";
        let cfg = K3sServerConfig::from_yaml(yaml).unwrap();
        assert_eq!(cfg.node_name, "x");
        assert!(cfg.extra.contains_key("unknown-operator-key"));
        assert!(cfg.extra.contains_key("nested-extra"));
        // Round-trip preserves them.
        let again = cfg.to_yaml();
        let body: String = again.lines().skip(1).collect::<Vec<_>>().join("\n");
        let reparsed = K3sServerConfig::from_yaml(&body).unwrap();
        assert_eq!(reparsed.extra, cfg.extra);
    }

    #[test]
    fn from_typed_inputs_constructor() {
        let cfg = K3sServerConfig::from_typed_inputs(
            "rio",
            PortRange::default(),
            &["rio.local".into(), "10.0.0.1".into()],
            Some(1450),
            Some("10.0.0.1".parse().unwrap()),
            Some("0.0.0.0".parse().unwrap()),
        );
        assert_eq!(cfg.node_name, "rio");
        assert!(cfg.service_node_port_range.unwrap().contains('-'));
        assert_eq!(cfg.tls_san.len(), 2);
        assert_eq!(cfg.flannel_iface_mtu, Some(1450));
    }
}
