//! Renderers — typed config → k3s flags / config.yaml / bootstrap manifests.
//!
//! Three load-bearing render paths:
//!
//! 1. [`ClusterConfig::render_k3s_config_yaml`] — emits the YAML k3s
//!    consumes from `/etc/rancher/k3s/config.yaml`. Covers most knobs
//!    (CIDRs, dns, node-port-range, tls-sans, mtu, ipv6, addresses).
//!
//! 2. [`ClusterConfig::render_k3s_server_args`] — extra `--flag=value`
//!    args appended to the k3s server command. Covers `--disable=…`,
//!    `--flannel-backend=…`, `--kube-proxy-arg=…`, `--disable-kube-proxy`,
//!    `--disable-network-policy`, `--cluster-init`.
//!
//! 3. [`ClusterConfig::render_bootstrap_manifests`] — emits CNI install
//!    manifests, ingress controller manifests, LB manifests, DNS overlay
//!    manifests, FluxCD install, ArgoCD install. Each manifest is
//!    keyed by filename for `/var/lib/rancher/k3s/server/manifests/`.

use indoc::formatdoc;

use crate::bootstrap::{ArgocdBootstrap, FluxcdBootstrap, SecretKind};
use crate::manifest::Manifest;
use crate::network::{
    CniChoice, DnsChoice, FlannelBackend, IngressChoice, K3sComponent,
    KubeProxyMode, LoadBalancerChoice, NetworkPolicyEnforce,
};
use crate::ClusterConfig;

impl ClusterConfig {
    /// Render the YAML body for `/etc/rancher/k3s/config.yaml`.
    #[must_use]
    pub fn render_k3s_config_yaml(&self) -> String {
        let net = &self.network;
        let mut sans = net.tls_sans.clone();
        sans.push(self.node_ip.to_string());
        sans.sort();
        sans.dedup();
        let sans_yaml = sans
            .iter()
            .map(|s| format!("  - {s}"))
            .collect::<Vec<_>>()
            .join("\n");

        // NOTE: cluster-cidr / service-cidr / cluster-dns are NOT
        // emitted here — the nixos-k3s-vm consumer sets them via
        // `services.blackmatter.k3s.{clusterCIDR,serviceCIDR,clusterDNS}`
        // (cmdline flags). Emitting them here ALSO would cause k3s to
        // see both values as a dual-stack list (config.yaml + cmdline
        // merged), failing with "must be of different IP family" when
        // dual_stack=false. dual-stack is rendered via cmdline overrides
        // by the consumer when dual_stack=true.
        let mut out = formatdoc! {"
            # Generated by engenho-cluster-config for {name}
            node-name: {name}
            service-node-port-range: {nps_start}-{nps_end}
            tls-san:
            {sans}
            ",
            name         = self.cluster_name,
            nps_start    = net.node_port_range.start,
            nps_end      = net.node_port_range.end,
            sans         = sans_yaml,
        };
        let _ = net.cluster_dns; // documented above: consumer-owned
        if let Some(mtu) = net.mtu {
            out.push_str(&format!("flannel-iface-mtu: {mtu}\n"));
        }
        if let Some(adv) = net.advertise_address {
            out.push_str(&format!("advertise-address: {adv}\n"));
        }
        if let Some(bind) = net.bind_address {
            out.push_str(&format!("bind-address: {bind}\n"));
        }
        out
    }

    /// Render the additional cmdline args appended after `k3s server`.
    /// These cover knobs not expressible (or not idiomatic) in
    /// `config.yaml`.
    #[must_use]
    pub fn render_k3s_server_args(&self) -> Vec<String> {
        let net = &self.network;
        let mut args: Vec<String> = Vec::new();

        // Disabled components — combine the explicit list with auto-
        // derivations from CNI / ingress / LB / DNS choices.
        let mut disable: Vec<K3sComponent> = net.disable_components.clone();
        // Non-default CNI ⇒ disable flannel.
        if !matches!(net.cni, CniChoice::Flannel) {
            // k3s exposes flannel-disable via `--flannel-backend=none`,
            // see below. No K3sComponent for it.
        }
        // Non-default ingress ⇒ disable traefik.
        if !matches!(net.ingress, IngressChoice::Traefik) {
            disable.push(K3sComponent::Traefik);
        }
        // Non-default LB ⇒ disable servicelb.
        if !matches!(net.load_balancer, LoadBalancerChoice::Servicelb) {
            disable.push(K3sComponent::Servicelb);
        }
        // External DNS ⇒ disable coredns.
        if matches!(net.dns, DnsChoice::External) {
            disable.push(K3sComponent::Coredns);
        }
        // network-policy=delegated|disabled ⇒ disable built-in controller.
        match net.network_policy.enforce {
            NetworkPolicyEnforce::Enabled => {}
            NetworkPolicyEnforce::Disabled | NetworkPolicyEnforce::Delegated => {
                disable.push(K3sComponent::NetworkPolicy);
            }
        }
        // kube-proxy disabled ⇒ disable
        if net.kube_proxy.disabled {
            disable.push(K3sComponent::KubeProxy);
        }
        disable.sort_by_key(|c| c.as_k3s_disable());
        disable.dedup();
        for c in &disable {
            args.push(format!("--disable={}", c.as_k3s_disable()));
        }

        // CNI selection.
        match net.cni {
            CniChoice::Flannel => {
                if let Some(b) = net.cni_backend {
                    args.push(format!("--flannel-backend={}", flannel_backend(b)));
                }
            }
            CniChoice::Calico | CniChoice::Cilium => {
                args.push("--flannel-backend=none".into());
                args.push("--disable-network-policy".into());
                args.push("--disable-kube-proxy".into());
            }
            CniChoice::None => {
                args.push("--flannel-backend=none".into());
                args.push("--disable-network-policy".into());
                args.push("--disable-cni".into());
            }
        }

        // kube-proxy mode (only when not disabled).
        if !net.kube_proxy.disabled
            && !matches!(net.kube_proxy.mode, KubeProxyMode::Iptables)
        {
            args.push(format!(
                "--kube-proxy-arg=proxy-mode={}",
                kube_proxy_mode(net.kube_proxy.mode)
            ));
        }

        args
    }

    /// Render the bootstrap manifests dropped into
    /// `/var/lib/rancher/k3s/server/manifests/`. k3s auto-applies the
    /// directory at startup. Order doesn't matter for k3s' apply loop
    /// (it's idempotent + retries), but the renderer emits a stable
    /// order keyed by filename for diff-stability.
    #[must_use]
    pub fn render_bootstrap_manifests(&self) -> Vec<Manifest> {
        let mut out: Vec<Manifest> = Vec::new();
        let net = &self.network;

        // CNI install manifests.
        match net.cni {
            CniChoice::Flannel | CniChoice::None => {} // built-in or operator-provided
            CniChoice::Calico  => out.push(calico_manifest()),
            CniChoice::Cilium  => out.push(cilium_manifest(net.kube_proxy.disabled)),
        }

        // Ingress controller manifests (only when non-default).
        match net.ingress {
            IngressChoice::Traefik     => {} // k3s default
            IngressChoice::Nginx       => out.push(nginx_ingress_manifest()),
            IngressChoice::Contour     => out.push(contour_manifest()),
            IngressChoice::GatewayApi  => out.push(gateway_api_manifest()),
            IngressChoice::None        => {} // operator-provided
        }

        // LoadBalancer manifests (only when non-default).
        match net.load_balancer {
            LoadBalancerChoice::Servicelb => {} // k3s default
            LoadBalancerChoice::Metallb   => out.push(metallb_manifest()),
            LoadBalancerChoice::KubeVip   => out.push(kubevip_manifest()),
            LoadBalancerChoice::None      => {} // operator-provided
        }

        // DNS overlay (nodelocal-dns when chosen).
        if matches!(net.dns, DnsChoice::NodelocalDns) {
            out.push(nodelocal_dns_manifest(net.cluster_dns));
        }

        // GitOps bootstrap.
        if self.bootstrap.fluxcd.enable {
            out.push(fluxcd_install_manifest(&self.bootstrap.fluxcd));
            if self.bootstrap.fluxcd.source.is_some() {
                out.push(fluxcd_source_manifest(&self.cluster_name, &self.bootstrap.fluxcd));
            }
        }
        if self.bootstrap.argocd.enable {
            out.push(argocd_install_manifest(&self.bootstrap.argocd));
            if self.bootstrap.argocd.source.is_some() {
                out.push(argocd_application_manifest(&self.cluster_name, &self.bootstrap.argocd));
            }
        }

        out.sort_by(|a, b| a.filename.cmp(&b.filename));
        out
    }
}

fn flannel_backend(b: FlannelBackend) -> &'static str {
    match b {
        FlannelBackend::Vxlan            => "vxlan",
        FlannelBackend::HostGw           => "host-gw",
        FlannelBackend::WireguardNative  => "wireguard-native",
        FlannelBackend::WireguardLegacy  => "wireguard",
        FlannelBackend::Ipsec            => "ipsec",
    }
}

fn kube_proxy_mode(m: KubeProxyMode) -> &'static str {
    match m {
        KubeProxyMode::Iptables => "iptables",
        KubeProxyMode::Ipvs     => "ipvs",
        KubeProxyMode::Nftables => "nftables",
    }
}

// ─────────────────────────────────────────────────────────────────────
// Manifest emitters — minimal HelmChart CRDs that k3s' helm-controller
// applies. Each manifest is one document; consumers can override
// `valuesContent` via downstream patches.
// ─────────────────────────────────────────────────────────────────────

fn calico_manifest() -> Manifest {
    Manifest::new("calico.yaml", formatdoc! {"
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: calico
          namespace: kube-system
        spec:
          repo: https://docs.tigera.io/calico/charts
          chart: tigera-operator
          targetNamespace: tigera-operator
          createNamespace: true
    "})
}

fn cilium_manifest(replace_kube_proxy: bool) -> Manifest {
    let replace = if replace_kube_proxy { "true" } else { "false" };
    Manifest::new("cilium.yaml", formatdoc! {"
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: cilium
          namespace: kube-system
        spec:
          repo: https://helm.cilium.io
          chart: cilium
          targetNamespace: kube-system
          valuesContent: |-
            kubeProxyReplacement: {replace}
            k8sServiceHost: 127.0.0.1
            k8sServicePort: 6443
    ", replace = replace})
}

fn nginx_ingress_manifest() -> Manifest {
    Manifest::new("ingress-nginx.yaml", formatdoc! {"
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: ingress-nginx
          namespace: kube-system
        spec:
          repo: https://kubernetes.github.io/ingress-nginx
          chart: ingress-nginx
          targetNamespace: ingress-nginx
          createNamespace: true
    "})
}

fn contour_manifest() -> Manifest {
    Manifest::new("contour.yaml", formatdoc! {"
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: contour
          namespace: kube-system
        spec:
          repo: https://charts.bitnami.com/bitnami
          chart: contour
          targetNamespace: projectcontour
          createNamespace: true
    "})
}

fn gateway_api_manifest() -> Manifest {
    // Gateway API requires both the CRDs and a controller. Envoy
    // Gateway is the upstream-recommended controller.
    Manifest::new("gateway-api.yaml", formatdoc! {"
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: envoy-gateway
          namespace: kube-system
        spec:
          repo: oci://docker.io/envoyproxy
          chart: gateway-helm
          targetNamespace: envoy-gateway-system
          createNamespace: true
    "})
}

fn metallb_manifest() -> Manifest {
    Manifest::new("metallb.yaml", formatdoc! {"
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: metallb
          namespace: kube-system
        spec:
          repo: https://metallb.github.io/metallb
          chart: metallb
          targetNamespace: metallb-system
          createNamespace: true
    "})
}

fn kubevip_manifest() -> Manifest {
    Manifest::new("kube-vip.yaml", formatdoc! {"
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: kube-vip
          namespace: kube-system
        spec:
          repo: https://kube-vip.github.io/helm-charts
          chart: kube-vip
          targetNamespace: kube-system
    "})
}

fn nodelocal_dns_manifest(cluster_dns: std::net::Ipv4Addr) -> Manifest {
    Manifest::new("nodelocal-dns.yaml", formatdoc! {"
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: nodelocal-dns
          namespace: kube-system
        spec:
          repo: https://kubernetes-sigs.github.io/nodelocaldns
          chart: nodelocaldns
          targetNamespace: kube-system
          valuesContent: |-
            clusterDNS: {dns}
    ", dns = cluster_dns})
}

fn fluxcd_install_manifest(cfg: &FluxcdBootstrap) -> Manifest {
    Manifest::new("flux-system-install.yaml", formatdoc! {"
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: flux2
          namespace: kube-system
        spec:
          repo: https://fluxcd-community.github.io/helm-charts
          chart: flux2
          version: {ver}
          targetNamespace: flux-system
          createNamespace: true
    ", ver = cfg.version})
}

fn fluxcd_source_manifest(cluster_name: &str, cfg: &FluxcdBootstrap) -> Manifest {
    let source = cfg.source.as_ref().expect("validate() guarantees Some when enable=true");
    let secret_ref = if source.auth.is_some() {
        formatdoc! {"
              secretRef:
                name: {name}
        ", name = format!("{cluster_name}-gitops-auth")}
    } else {
        String::new()
    };
    let body = formatdoc! {"
        ---
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: GitRepository
        metadata:
          name: {name}
          namespace: flux-system
        spec:
          interval: {interval}
          url: {url}
          ref:
            branch: {branch}
        {secret_ref}---
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: {name}
          namespace: flux-system
        spec:
          interval: {interval}
          path: {path}
          prune: true
          sourceRef:
            kind: GitRepository
            name: {name}
        ",
        name     = cluster_name,
        interval = cfg.interval,
        url      = source.url,
        branch   = source.branch,
        path     = cfg.path,
        secret_ref = secret_ref,
    };
    let mut m = Manifest::new("flux-system-source.yaml", body);
    if let Some(auth) = &source.auth {
        m.body.push_str(&render_gitops_secret_placeholder(cluster_name, auth.kind));
    }
    m
}

fn argocd_install_manifest(cfg: &ArgocdBootstrap) -> Manifest {
    Manifest::new("argocd-install.yaml", formatdoc! {"
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: argo-cd
          namespace: kube-system
        spec:
          repo: https://argoproj.github.io/argo-helm
          chart: argo-cd
          version: {ver}
          targetNamespace: argocd
          createNamespace: true
    ", ver = cfg.version})
}

fn argocd_application_manifest(cluster_name: &str, cfg: &ArgocdBootstrap) -> Manifest {
    let source = cfg.source.as_ref().expect("validate() guarantees Some when enable=true");
    let target_rev = cfg.target_revision.clone().unwrap_or_else(|| source.branch.clone());
    Manifest::new("argocd-application.yaml", formatdoc! {"
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: {name}-root
          namespace: argocd
        spec:
          project: default
          source:
            repoURL: {url}
            targetRevision: {target_rev}
            path: {path}
          destination:
            server: https://kubernetes.default.svc
            namespace: argocd
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
    ",
        name       = cluster_name,
        url        = source.url,
        target_rev = target_rev,
        path       = cfg.path,
    })
}

fn render_gitops_secret_placeholder(cluster_name: &str, kind: SecretKind) -> String {
    // The actual credential value is materialized by sops-nix at
    // activation time. The nixos-k3s-vm consumer is responsible for
    // declaring the matching `sops.secrets.<sops_key>` + dropping the
    // populated YAML in place of this placeholder.
    let (secret_type, data_key) = match kind {
        SecretKind::HttpsToken => ("kubernetes.io/basic-auth", "password"),
        SecretKind::SshKey     => ("kubernetes.io/ssh-auth",   "identity"),
    };
    formatdoc! {"
        ---
        apiVersion: v1
        kind: Secret
        type: {secret_type}
        metadata:
          name: {name}-gitops-auth
          namespace: flux-system
        stringData:
          username: oauth2  # ignored for ssh-auth
          {data_key}: REPLACED-BY-SOPS-NIX-ACTIVATION
    ",
        secret_type = secret_type,
        name        = cluster_name,
        data_key    = data_key,
    }
}
